# SPDX-FileCopyrightText: 2022 Winni Neessen <winni@neessen.dev>
#
# SPDX-License-Identifier: CC0-1.0

name: SonarQube

permissions:
  contents: read

on:
  push:
    branches:
      - main # or the name of your main branch
  pull_request:
    branches:
      - main # or the name of your main branch
env:
  TEST_HOST: ${{ secrets.TEST_HOST }}
  TEST_FROM: ${{ secrets.TEST_USER }}
  TEST_ALLOW_SEND: "1"
  TEST_SMTPAUTH_USER: ${{ secrets.TEST_USER }}
  TEST_SMTPAUTH_PASS: ${{ secrets.TEST_PASS }}
  TEST_SMTPAUTH_TYPE: "LOGIN"
  TEST_ONLINE_SCRAM: "1"
  TEST_HOST_SCRAM: ${{ secrets.TEST_HOST_SCRAM }}
  TEST_USER_SCRAM: ${{ secrets.TEST_USER_SCRAM }}
  TEST_PASS_SCRAM: ${{ secrets.TEST_PASS_SCRAM }}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
        with:
          fetch-depth: 0
          
      - name: Setup Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: '1.23.x'
          
      - name: Run unit Tests
        run: |
          go test -shuffle=on -race --coverprofile=./cov.out ./...

      - uses: sonarsource/sonarqube-scan-action@884b79409bbd464b2a59edc326a4b77dc56b2195 # master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          
      - uses: sonarsource/sonarqube-quality-gate-action@dc2f7b0dd95544cd550de3028f89193576e958b9 # master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
